- .idea/misc.xml
- .idea/modules.xml
- app/src/main/java/com/example/baard/User.java
- app/src/test/java/com/example/baard/UserListTest.java
- app/src/test/java/com/example/baard/UserTest.java
Initial tests for the User and the UserList class
> Daniel test

- .idea/modules.xml
- app/src/main/java/com/example/baard/LoginActivity.java
- app/src/main/res/layout/activity_login.xml
- app/src/main/res/values/strings.xml
No server implementation, but updated interface and regex checking.
> Basic Login Activity

- app/src/main/java/com/example/baard/AllHabitsFragment.java
- app/src/main/java/com/example/baard/CreateNewHabitFragment.java
- app/src/main/java/com/example/baard/EditHabitActivity.java
- app/src/main/java/com/example/baard/ElasticSearchController.java
- app/src/main/java/com/example/baard/HabitList.java
- app/src/main/java/com/example/baard/LoginActivity.java
- app/src/main/java/com/example/baard/MainActivity.java
- app/src/main/java/com/example/baard/User.java
- app/src/main/java/com/example/baard/ViewHabitActivity.java
Create
View
Edit
Delete
Functionality done for habits
> Habit backend complete with elastic search 

- app/src/main/java/com/example/baard/LoginActivity.java
- app/src/main/java/com/example/baard/MainActivity.java
- app/src/main/res/layout/activity_login.xml
- app/src/main/res/menu/activity_main_drawer.xml
if user logged out, then they need internet to log in!
> auto-login if user never logged out

- app/build.gradle
- app/src/main/java/com/example/baard/DailyHabitsFragment.java
- app/src/main/java/com/example/baard/HabitList.java
- app/src/main/java/com/example/baard/MainActivity.java
- app/src/main/res/layout/fragment_daily_habits.xml
You'll see that the layout is essentially the same as All Habits. 
Filtering uses a for loop that just stores any that match today to be in the dailyHabitList;
I didn't actually modify the build gradle, it just ordered them sequentially like that when I reopened the project.
> Daily habits

- app/src/main/java/com/example/baard/EditHabitEventActivity.java
Fixed the image display bug. It was just me not calling the function, no actual bug.
> fixed image not displaying in EditHabitEventActivity

- app/src/main/java/com/example/baard/ViewHabitActivity.java
- app/src/main/res/layout/activity_view_habit.xml
Probably best to run the branch to test. The mass changes in the xml are hard to understand.
Mostly got rid of 7 nested layouts..
> Event list in View habit

- app/src/main/java/com/example/baard/EditHabitEventActivity.java
- app/src/main/java/com/example/baard/ViewHabitEventActivity.java
Did not modify passing intents between allHabitEventsList and ViewHabitEvent. 
Used the intent result I showed Bianca in class.
> Back button functionality for EditHabitEventActivity

- app/src/main/java/com/example/baard/AllHabitsFragment.java
- app/src/main/java/com/example/baard/DailyHabitsFragment.java
- app/src/main/java/com/example/baard/ExpandableListAdapter.java
- app/src/main/res/layout/fragment_all_habits.xml
- app/src/main/res/layout/fragment_daily_habits.xml
- app/src/main/res/layout/list_group.xml
- app/src/main/res/layout/list_item_expandable.xml
In Daily Habits and All Habits
> Expandable List Views

- app/src/main/java/com/example/baard/DailyHabitsFragment.java
- app/src/main/java/com/example/baard/EditHabitActivity.java
- app/src/main/java/com/example/baard/EditHabitEventActivity.java
- app/src/main/java/com/example/baard/MainActivity.java
- app/src/main/java/com/example/baard/ViewHabitActivity.java
- app/src/main/java/com/example/baard/ViewHabitEventActivity.java
- app/src/main/res/layout/activity_edit_habit_event.xml
- app/src/main/res/layout/activity_view_habit.xml
- app/src/main/res/layout/activity_view_habit_event.xml
- app/src/main/res/layout/fragment_daily_habits.xml
- app/src/main/res/values/strings.xml
Events in view habit are now clickable and take you to view habit event.
Added titles to all activities in the toolbar
Added strings to everything about Daily Habits
Ran Analyze -> inspect code on Daily and Main Activities
Cleaned up / Standardized some XML layouts (indentation, etc.)
Delete this branch upon merge
> Event list in view habit now clickable + Strings everywhere and cleaning up xmls

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/baard/MainActivity.java
- app/src/main/java/com/example/baard/SettingsActivity.java
- app/src/main/res/layout/activity_settings.xml
- app/src/main/res/menu/activity_main_drawer.xml
- app/src/main/res/values/strings.xml
Allows users to:
- view their username and name
- edit name
- delete account (functionality to come -- currently set to "coming soon")
> Settings Page 

- app/src/main/java/com/example/baard/CreateNewHabitEventFragment.java
- app/src/main/java/com/example/baard/CreateNewHabitFragment.java
- app/src/main/java/com/example/baard/DailyHabitsFragment.java
- app/src/main/java/com/example/baard/LoginActivity.java
- app/src/main/java/com/example/baard/MainActivity.java
Back buttons between fragments
Back button from main to Login
Back buttons after creating habits and events
> Login and main and back and stuff

- app/src/main/java/com/example/baard/HabitEvent.java
This fixes the bug for not being able to view habit event and habit event list.
> changed toString method for HabitEvent class

- app/src/main/java/com/example/baard/CreateNewHabitEventFragment.java
- app/src/main/java/com/example/baard/EditHabitEventActivity.java
- app/src/main/java/com/example/baard/HabitEvent.java
- app/src/main/java/com/example/baard/SerializableImage.java
- app/src/main/java/com/example/baard/ViewHabitEventActivity.java
- app/src/main/res/layout/fragment_create_new_habit_event.xml
serializes images in server, provided they are not too big (65536 bytes)
> Image serialization

- app/src/main/java/com/example/baard/CreateNewHabitEventFragment.java
- app/src/main/java/com/example/baard/Habit.java
> Milestone update for new date formatting

- app/src/main/java/com/example/baard/FileController.java
- app/src/main/java/com/example/baard/LoginActivity.java
Should allow for modifying anything. 
Also allows for relogin to last account while offline if you mess up and accidentally log out while offline.
> Offline Behaviour Improved

- app/src/main/java/com/example/baard/FileController.java
- app/src/main/java/com/example/baard/Habit.java
- app/src/main/java/com/example/baard/HabitEventList.java
- app/src/main/java/com/example/baard/HelpFragment.java
- app/src/main/java/com/example/baard/MainActivity.java
- app/src/main/java/com/example/baard/SettingsActivity.java
- app/src/main/java/com/example/baard/User.java
- app/src/main/java/com/example/baard/ViewHabitActivity.java
- app/src/main/res/layout/activity_settings.xml
- app/src/main/res/layout/fragment_help.xml
- app/src/main/res/menu/activity_main_drawer.xml
- app/src/main/res/values/strings.xml
- Adds functionality for friends in the FileController
- fixes issue with streak counting one less
- fixes sticky keyboard issue for settings 
- adds a help window to explain milestones and streaks
> Friend request controller addition, streaks fix, settings fix, and help menu

- app/src/main/java/com/example/baard/DailyHabitsFragment.java
- app/src/main/java/com/example/baard/FileController.java
- app/src/main/java/com/example/baard/LoginActivity.java
- app/src/main/java/com/example/baard/MainActivity.java
- app/src/main/java/com/example/baard/SettingsActivity.java
- app/src/main/res/menu/main.xml
- app/src/main/res/values/strings.xml
this comes with greater error handling on login with @anarten
> Settings cleanup and can now delete account

- app/src/androidTest/java/com/example/baard/CreateHabitEventTest.java
- app/src/androidTest/java/com/example/baard/DeleteHabitEventTest.java
- app/src/androidTest/java/com/example/baard/EditHabitEventTest.java
creating habit event tests are done, edit habit event test class created but not implemented
> Create habit event tests

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/baard/ViewFriendActivity.java
- app/src/main/java/com/example/baard/ViewFriendHabitActivity.java
- app/src/main/res/layout/activity_view_friend.xml
- app/src/main/res/layout/activity_view_friend_habit.xml
- app/src/main/res/values/strings.xml
You can now view a friend when you click on them in the friend list, and then view a habit, along with their most recent habit event. It does not actually grab the friends data right now, its just grabbing the currently logged in user's stuff for a placeholder.
> View friends

- app/src/main/java/com/example/baard/AllHabitEventsFragment.java
- app/src/main/java/com/example/baard/ExpandableListAdapter.java
- app/src/main/java/com/example/baard/Habit.java
- app/src/main/java/com/example/baard/HabitEvent.java
- app/src/main/java/com/example/baard/ViewHabitActivity.java
- app/src/main/res/layout/fragment_all_habit_events.xml
- app/src/main/res/layout/list_group.xml
- app/src/main/res/layout/list_item_event_expandable.xml
- app/src/main/res/layout/list_item_expandable.xml
Including some toast fixes and filter formatting and other little trickles
> Expandable events list

- app/src/main/java/com/example/baard/AlarmReceiver.java
Also only one notification will appear at most
> Fixed notifications to be expandable

- .idea/misc.xml
- app/src/main/java/com/example/baard/HabitEvents/CreateNewHabitEventFragment.java
- app/src/main/java/com/example/baard/HabitEvents/EditHabitEventActivity.java
- app/src/test/java/com/example/baard/HabitStatisticsTest.java
Can now remove images when creating/editing a habit event
> Remove images

- app/src/androidTest/java/com/example/baard/CreateHabitEventTest.java
- app/src/androidTest/java/com/example/baard/DeleteHabitEventTest.java
- app/src/androidTest/java/com/example/baard/EditHabitEventTest.java
- app/src/test/java/com/example/baard/HabitStatisticsTest.java
Fixed CreateHabitEventTest and EditHabitEventTest to all pass (at least on my machine), and added javadoc/cleaned comments from those classes as well as others.
> Habit event testing

- app/src/main/java/com/example/baard/HabitEvents/AllHabitEventsFragment.java
- app/src/main/java/com/example/baard/HabitEvents/CreateNewHabitEventFragment.java
- app/src/main/java/com/example/baard/HabitEvents/EditHabitEventActivity.java
- app/src/main/java/com/example/baard/HabitEvents/ViewHabitEventActivity.java
All files in HabitEvents folders had some updated javadoc
> updated javadoc for a number of functions

- app/src/androidTest/java/com/example/baard/AllHabitsTest.java
- app/src/androidTest/java/com/example/baard/DailyHabitsTest.java
> Daily and All Habits Tests Update
